name: nexus-core
version: 1.0.0
author: lovetwice1012
api: 4.0.0
main: nexuscore\nexuscore
description: Nexusのコアプラグインです。
commands:
    rand:
        description: 乱数を発生させます。
        usage: /rand min max <true | false>
    mywarp:
        description: 個人用のワープ地点を登録できます。
        usage: /mywarp
    myw:
        description: 個人用のワープ地点を登録できます。
        usage: /myw
    tpp:
        description: プレイヤーに転送リクエストを送信できます。
        usage: /tpp playername
permissions:
    nexuscore.rand:
        default: true
    nexuscore.mywarp:
        default: true
    nexuscore.myw:
        default: true
    nexuscore.tpp:
        default: true